name: Run unit tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.os }}
      uses: actions/setup-python@v3
    - name: Test with unittest
      run: |
        python -m unittest -v
